
site_name: Kennisbank SV Wezep
repo_url: https://github.com/svwezep/kennisbank
repo_name: kennisbank
edit_uri: edit/master/docs
extra_css:
  - assets/style.css
plugins:
  - search: {}
  - encryptcontent: 
      global_password: 'jaap'
      title_prefix: ''
      summary: 'Geen toegang'
      placeholder: 'wachtwoord'      
      encryption_info_message: "Voer het wachtwoord in om de inhoud te zien (Wat is de voornaam van de voorzitter)"
theme:
  name: material
  logo: assets/SV-Wezep-Logo-64px.png
  favicon: assets/SV-Wezep-Logo-32px.png
  language: nl
  palette: 
    scheme: default
    primary: red
    accent: blue
  features:
    - navigation.sections
    - navigation.expand    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  generator: false
copyright: Copyright &copy; Schietvereniging Wezep

nav:
  
  - Algemeen:
    - Opleiding tot vuurschutter: algemeen/opleiding-tot-vuurschutter.md
    - Over de vereniging: algemeen/over-de-vereniging.md
    - Lidmaatschap en contributie: algemeen/lidmaatschap-en-contributie.md
    - Vrijwilligers en taken: algemeen/vrijwilligers-en-taken.md

  - Veiligheid:
        
    - Wet en regelgeving: veiligheid/wet-en-regelgeving.md
    - Uitgifte / inname wapens: veiligheid/wapenuitgifte.md
    - Veiligheid op de baan: veiligheid/veiligheid-op-de-baan.md    
    - Verenigingsveiligheidsfunctionaris (VVF): veiligheid/verenigingsveiligheidsfunctionaris.md
    - Bedrijfshulpverlening (BHV): veiligheid/bedrijfshulpverlening.md

  - Techniek: 
    - Schiettechniek en houding: techniek/schiettechniek-en-houding.md
    - Informatie over munitie: techniek/instructie-munitie.md
    - Instructies gebruik pistool: techniek/instructie-pistool.md
    - Instructies gebruik revolver: techniek/instructie-revolver.md
    - Instructies gebruik karabijn: techniek/instructie-karabijn.md
    - Instructies gebruik geweer: techniek/instructie-geweer.md

  - Overig:
    - Wisselen plankje: overig/wisselen-plankje (kaarthouder).md
    - Opbouwen/afbreken schietbaan: overig/opbouwen-afbreken-attributen (schietbaan).md
